---
title: "DataManip"
author: "Danielle Ethier"
date: "18/12/2020"
output: html_document
---

This code was written to facilitate CMMN trend comparision using variour response variables: DET, Band, Census, Band+Census. The raw output used for this analysis can be found in the `data` folder. 


```{r load packages, include=FALSE, echo=FALSE}

library(tidyverse)
library(reshape)
library(ggplot2)
library(lmodel2) #Reduced major axis regression

#custom function to plot multiple plots per page
source("./multiplotfunction.R")

```

Now we will bulk import the data 

```{r import trend data, include=FALSE, echo=FALSE}

require(plyr)

mydir<-"data/"
my.files<-list.files(path = mydir, patter ="*det.Trends.2018.csv", full.name=TRUE)
DETtrend<-ldply(my.files, read.csv)
DETtrend$Response<-"DET"

my.files<-list.files(path = mydir, patter ="*band.Trends.2018.csv", full.name=TRUE)
Bandtrend<-ldply(my.files, read.csv)
Bandtrend$Response<-"Band"

my.files<-list.files(path = mydir, patter ="*census.Trends.2018.csv", full.name=TRUE)
Censustrend<-ldply(my.files, read.csv)
Censustrend$Response<-"Census"

my.files<-list.files(path = mydir, patter ="*bc.Trends.2018.csv", full.name=TRUE)
BCtrend<-ldply(my.files, read.csv)
BCtrend$Response<-"BandCensus"

BBStrend<-read.csv(paste0(mydir, "BBStrends.csv"))
BBStrend$Response<-"BBS"

detach(package:plyr) #detach or this will cause an issue with dplyr

```

```{r import index data, include=FALSE, echo=FALSE}

require(plyr)

mydir<-"data/"
my.files<-list.files(path = mydir, patter ="*det.AnnualIndices.2018.csv", full.name=TRUE)
DETindex<-ldply(my.files, read.csv)
DETindex$Response<-"DET"

my.files<-list.files(path = mydir, patter ="*band.AnnualIndices.2018.csv", full.name=TRUE)
Bandindex<-ldply(my.files, read.csv)
Bandindex$Response<-"Band"

my.files<-list.files(path = mydir, patter ="*census.AnnualIndices.2018.csv", full.name=TRUE)
Censusindex<-ldply(my.files, read.csv)
Censusindex$Response<-"Census"

my.files<-list.files(path = mydir, patter ="*bc.AnnualIndices.2018.csv", full.name=TRUE)
BCindex<-ldply(my.files, read.csv)
BCindex$Response<-"BandCensus"

```

```{r compile, include=FALSE, echo=FALSE}

#combine cmmn output
cmmntrend<-rbind(Bandtrend, BCtrend, Censustrend, DETtrend)
cmmnindex<-rbind(Bandindex, BCindex, Censusindex, DETindex)

#select desired columns
cmmntrend<-cmmntrend %>% select(SpeciesCode, english_name, trnd, lower_ci, upper_ci, post_prob, period, years, season, analysis_code, site, Response)

cmmnindex<-cmmnindex %>% select(SpeciesCode, english_name, index, lower_ci, upper_ci, period, year, season, analysis_code, site, Response)

#set filters
cmmntrend<- cmmntrend %>% filter(years=="2008-2018") %>%  filter(analysis_code=="M") %>% droplevels()

cmmnindex<- cmmnindex %>% filter(year>=2008) %>%  filter(analysis_code=="M") %>% droplevels()

#remove NAs
#cmmntrend<-na.omit(cmmntrend)

```

```{r plottrends, include=FALSE, echo=FALSE}
site.list<-unique(cmmntrend$site)

#create a site specific loop 
for(m in 1:length(site.list)) {
  
#m<-1 #for testing
    
  site.data <-NULL 
  site.data <- filter(cmmntrend, site == site.list[m]) %>%
      droplevels()
  
site<-unique(site.data$site) 

#recast the dataframe

site.data<-cast(site.data, SpeciesCode+season~Response, value="trnd")

p1<-ggplot(data=site.data, aes(DET, BandCensus, colour=season))+
  geom_point(show.legend = FALSE)+
  theme_classic()+
  xlab("")
p2<-ggplot(data=site.data, aes(DET, Census, colour=season))+
  geom_point(show.legend = FALSE)+
  theme_classic()+
  xlab("")
p3<-ggplot(data=site.data, aes(DET, Band, colour=season))+
  geom_point()+
  theme_classic()+
  theme(legend.position="bottom")
  
pdf(paste(site, "trend.compare.plots.pdf"))
multiplot(p1, p2, p3) 
while(!is.null(dev.list())) dev.off()
  
} #end site specific loop

trend.summary<-cast(cmmntrend, SpeciesCode+season+site~Response, value="trnd")
trend.summary<-trend.summary %>% drop_na("DET")

p1<-ggplot(data=trend.summary, aes(DET, BandCensus, colour=season))+
  geom_point(show.legend = FALSE)+
  theme_classic()+
  xlab("")
p2<-ggplot(data=trend.summary, aes(DET, Census, colour=season))+
  geom_point(show.legend = FALSE)+
  theme_classic()+
  xlab("")
p3<-ggplot(data=trend.summary, aes(DET, Band, colour=season))+
  geom_point()+
  theme_classic()+
  theme(legend.position="bottom")

pdf(paste("full.trend.compare.plots.pdf"))
multiplot(p1, p2, p3) 
while(!is.null(dev.list())) dev.off()
  
```

```{r plotindex, include=FALSE, echo=FALSE}
site.list<-unique(cmmnindex$site)

#create a site specific loop 
for(m in 1:length(site.list)) {
  
#m<-1 #for testing
    
  site.data <-NULL 
  site.data <- filter(cmmnindex, site == site.list[m]) %>%
      droplevels()
  
site<-unique(site.data$site) 

#recast the dataframe

site.data<-cast(site.data, SpeciesCode+season+year~Response, value="index")

p1<-ggplot(data=site.data, aes(DET, BandCensus, colour=season))+
  geom_point(show.legend = FALSE)+
  theme_classic()+
  xlab("")
p2<-ggplot(data=site.data, aes(DET, Census, colour=season))+
  geom_point(show.legend = FALSE)+
  theme_classic()+
  xlab("")
p3<-ggplot(data=site.data, aes(DET, Band, colour=season))+
  geom_point()+
  theme_classic()+
  theme(legend.position="bottom")
  
pdf(paste(site, "index.compare.plots.pdf"))
multiplot(p1, p2, p3) 
while(!is.null(dev.list())) dev.off()
  
} #end site specific loop

```

Will use a reduced major axis regression

```{trend regression include=FALSE, echo=FALSE}

mod1<-lmodel2(DET~Band,data=trend.summary,"interval","interval",99)
mod2<-lmodel2(DET~Census,data=trend.summary,"interval","interval",99)
mod3<-lmodel2(DET~BandCensus,data=trend.summary,"interval","interval",99)
mod4<-lmodel2(Census~Band,data=trend.summary,"interval","interval",99)

#mod1$regression.results #to print results

# wanted results from the RMA model
INT <- mod1$regression.results[[2]][4]
SLOPE <- mod1$regression.results[[3]][4]
PVAL <- mod1$P.param
RSQ <- mod1$rsquare
Model<-"DET vs. Band"
DET.band = data.frame(cbind(Model, INT, SLOPE, PVAL, RSQ))

INT <- mod2$regression.results[[2]][4]
SLOPE <- mod2$regression.results[[3]][4]
PVAL <- mod2$P.param
RSQ <- mod2$rsquare
Model<-"DET vs. Census"
DET.census = data.frame(cbind(Model, INT, SLOPE, PVAL, RSQ))

INT <- mod3$regression.results[[2]][4]
SLOPE <- mod3$regression.results[[3]][4]
PVAL <- mod3$P.param
RSQ <- mod3$rsquare
Model<-"DET vs. Band+Census"
DET.bandcensus = data.frame(cbind(Model, INT, SLOPE, PVAL, RSQ))

INT <- mod4$regression.results[[2]][4]
SLOPE <- mod4$regression.results[[3]][4]
PVAL <- mod4$P.param
RSQ <- mod4$rsquare
Model<-"Band vs. Census"
band.census = data.frame(cbind(Model, INT, SLOPE, PVAL, RSQ))

trend.regression<-rbind(DET.band, DET.census, DET.bandcensus, band.census)
trend.regression$INT<-as.numeric(trend.regression$INT, round=3)
trend.regression$SLOPE<-as.numeric(trend.regression$SLOPE, round=3)
trend.regression$PVAL<-as.numeric(trend.regression$PVAL, round=3)
trend.regression$RSQ<-as.numeric(trend.regression$RSQ, round=3)

```


