---
title: "Plotting"
author: "Danielle Ethier"
date: "25/01/2021"
output: html_document
---

#This step plots the raw trend and index values for visual inspection. Will remove any extreme outliers. 


```{r plottrends, include=FALSE, echo=FALSE}
site.list<-unique(cmmntrend$site)

#create a site specific loop 
for(m in 1:length(site.list)) {
  
#m<-1 #for testing
    
  site.data <-NULL 
  site.data <- filter(cmmntrend, site == site.list[m]) %>%
      droplevels()
  
site<-unique(site.data$site) 

#recast the dataframe

site.data<-cast(site.data, SpeciesCode+season~Response, value="trnd")

p1<-ggplot(data=site.data, aes(DET, BandCensus, colour=season))+
  geom_point(show.legend = FALSE)+
  theme_classic()+
  xlab("")
p2<-ggplot(data=site.data, aes(DET, Census, colour=season))+
  geom_point(show.legend = FALSE)+
  theme_classic()+
  xlab("")
p3<-ggplot(data=site.data, aes(DET, Band, colour=season))+
  geom_point()+
  theme_classic()+
  theme(legend.position="bottom")
  
pdf(paste(site, "trend.compare.plots.pdf"))
multiplot(p1, p2, p3) 
while(!is.null(dev.list())) dev.off()
  
} #end site specific loop

trend.summary<-cast(cmmntrend, SpeciesCode+season+site~Response, value="trnd")
trend.summary<-trend.summary %>% drop_na("DET")

p1<-ggplot(data=trend.summary, aes(DET, BandCensus, colour=season))+
  geom_point(show.legend = FALSE)+
  theme_classic()+
  xlab("")
p2<-ggplot(data=trend.summary, aes(DET, Census, colour=season))+
  geom_point(show.legend = FALSE)+
  theme_classic()+
  xlab("")
p3<-ggplot(data=trend.summary, aes(DET, Band, colour=season))+
  geom_point()+
  theme_classic()+
  theme(legend.position="bottom")

pdf(paste("full.trend.compare.plots.pdf"))
multiplot(p1, p2, p3) 
while(!is.null(dev.list())) dev.off()
  
```


```{r plotindex, include=FALSE, echo=FALSE}
site.list<-unique(cmmnindex$site)

#create a site specific loop 
for(m in 1:length(site.list)) {
  
#m<-1 #for testing
    
  site.data <-NULL 
  site.data <- filter(cmmnindex, site == site.list[m]) %>%
      droplevels()
  
site<-unique(site.data$site) 

#remove extreme outliers
site.data<-site.data %>% filter(index <= 30) %>%  filter(index >= -30)

#recast the dataframe

site.data<-cast(site.data, SpeciesCode+season+year~Response, value="index")

#no data output for Fall 2008 at TTPBRS
if(site=="TTPBRS"){
  site.data<-site.data %>% filter(!(season == "Fall" & year == 2008))
}

p1<-ggplot(data=site.data, aes(DET, BandCensus, colour=season))+
  geom_point(show.legend = FALSE)+
  theme_classic()+
  xlab("")
p2<-ggplot(data=site.data, aes(DET, Census, colour=season))+
  geom_point(show.legend = FALSE)+
  theme_classic()+
  xlab("")
p3<-ggplot(data=site.data, aes(DET, Band, colour=season))+
  geom_point()+
  theme_classic()+
  theme(legend.position="bottom")
  
pdf(paste(site, "index.compare.plots.pdf"))
multiplot(p1, p2, p3) 
while(!is.null(dev.list())) dev.off()
  
} #end site specific loop

```